### ISSUE TITLE
Unexpected Wall Installation in Game Board Boundary

### ISSUE THREAD

**Issue by ChoiCube84** [dastyinc/loq0#6]
I have come across an unexpected behavior where walls are being installed within the boundaries of the game board.

**Expected Behavior:**
I expected that the game board boundaries would restrict the placement of I-shaped walls.

**Actual Behavior:**
Walls are finding their way into the boundaries of the game board. Specifically, horizontal I-shaped walls can be placed in positions with y coordinates ranging from 1 to 10. Similarly, vertical I-shaped walls can be placed in positions with x coordinates ranging from 1 to 10.

I would appreciate it if the development team could investigate this issue and, if deemed necessary, make the appropriate adjustments to rectify the problem.

Thank you.

**Comment by seo-rii** [comment]
This is intended behaior. Since we couldn't determine the rules for how to handle it in relation to the edge, we specified that we could arbitrarily place blocks on the edge. I think it should be designated as a rule because it can affect the play of the game. For example, by placing an L-shaped block on the edge, you can create a block of 1 length that interferes with the opponent's game. We will ask the steering committee about this and proceed with the patch according to the results.
